services:
  app:
    build: .
    container_name: excel2json
    volumes:
      - .:/app
    networks:
      - app
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.16-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app
      - backbone

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - backbone

networks:
  app: {}
  backbone: {}
